language: ruby

bundler_args: "--binstubs --standalone --without documentation --path ../bundle"

script: "bundle exec rake test"

gemfile:
  - gemfiles/sprockets_2_12.gemfile
  - gemfiles/sprockets_3_0.gemfile
  - gemfiles/rails_3_2.gemfile

rvm:
  - 2.2.2

notifications:
  email: false
